name: Scheduled Job

on:
  workflow_dispatch:
  schedule:
    - cron: '* 13 * * *'

jobs:
  event_alert:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: docker build -t event-notifier .

    - name: Run Docker Container
      run: |
        docker run \
          -e PUSHOVER_USER_KEY=${{ secrets.PUSHOVER_USER_KEY }} \
          -e PUSHOVER_API_TOKEN=${{ secrets.PUSHOVER_API_TOKEN }} \
          event-notifier
